#!/bin/bash
# deploy.sh - Cloud Run Deployment Script
# Generated by cloudrun-deploy skill

set -e  # Exit on error

# ============================================================================
# Configuration
# ============================================================================

PROJECT_ID="${PROJECT_ID:-your-project-id}"
SERVICE_NAME="${SERVICE_NAME:-your-service}"
REGION="${REGION:-europe-west2}"
IMAGE_URL="gcr.io/${PROJECT_ID}/${SERVICE_NAME}:latest"

# ============================================================================
# Colors for output
# ============================================================================

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# ============================================================================
# Functions
# ============================================================================

check_prerequisites() {
    log_info "Checking prerequisites..."

    command -v docker >/dev/null 2>&1 || { log_error "Docker is required but not installed."; exit 1; }
    command -v terraform >/dev/null 2>&1 || { log_error "Terraform is required but not installed."; exit 1; }
    command -v gcloud >/dev/null 2>&1 || { log_error "gcloud CLI is required but not installed."; exit 1; }

    # Check Docker is running
    docker info >/dev/null 2>&1 || { log_error "Docker is not running."; exit 1; }

    log_info "All prerequisites met."
}

build_image() {
    log_info "Building Docker image..."
    docker build -t "${IMAGE_URL}" .
    log_info "Image built: ${IMAGE_URL}"
}

push_image() {
    log_info "Pushing image to registry..."
    docker push "${IMAGE_URL}"
    log_info "Image pushed: ${IMAGE_URL}"
}

deploy_infrastructure() {
    log_info "Deploying infrastructure..."
    cd infrastructure

    # Initialize Terraform if needed
    if [ ! -d ".terraform" ]; then
        log_info "Initializing Terraform..."
        terraform init
    fi

    # Plan and apply
    log_info "Planning changes..."
    terraform plan -out=tfplan

    log_info "Applying changes..."
    terraform apply tfplan

    # Clean up plan file
    rm -f tfplan

    cd ..
    log_info "Infrastructure deployed."
}

verify_deployment() {
    log_info "Verifying deployment..."

    SERVICE_URL=$(cd infrastructure && terraform output -raw service_url)

    log_info "Service URL: ${SERVICE_URL}"

    # Wait for service to be ready
    log_info "Waiting for service to be ready..."
    sleep 5

    # Test health endpoint
    HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "${SERVICE_URL}/health" || echo "000")

    if [ "$HTTP_STATUS" = "200" ]; then
        log_info "Health check passed!"
    else
        log_warn "Health check returned status: ${HTTP_STATUS}"
        log_warn "Service may still be starting up. Check logs:"
        echo "  gcloud run services logs read ${SERVICE_NAME} --region=${REGION} --limit=20"
    fi
}

show_status() {
    log_info "Deployment complete!"
    echo ""
    echo "Service Details:"
    echo "  Name:   ${SERVICE_NAME}"
    echo "  Region: ${REGION}"
    echo "  URL:    $(cd infrastructure && terraform output -raw service_url)"
    echo ""
    echo "Useful commands:"
    echo "  View logs:    gcloud run services logs read ${SERVICE_NAME} --region=${REGION}"
    echo "  List revisions: gcloud run revisions list --service=${SERVICE_NAME} --region=${REGION}"
    echo "  Describe:     gcloud run services describe ${SERVICE_NAME} --region=${REGION}"
}

# ============================================================================
# Main
# ============================================================================

main() {
    echo "========================================"
    echo "Cloud Run Deployment: ${SERVICE_NAME}"
    echo "========================================"
    echo ""

    check_prerequisites
    build_image
    push_image
    deploy_infrastructure
    verify_deployment
    show_status
}

# Run if executed directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
