# iam.tf - Service Account and IAM Bindings
# Generated by cloudrun-deploy skill

# Runtime service account for the Cloud Run service
resource "google_service_account" "runtime" {
  account_id   = "${var.service_name}-runtime"
  display_name = "Runtime service account for ${var.service_name}"
  description  = "Service account used by Cloud Run service ${var.service_name}"
}

# ============================================================================
# Common IAM Bindings
# Add/remove bindings based on service dependencies
# ============================================================================

# Cloud Storage access (uncomment if needed)
# resource "google_project_iam_member" "storage_viewer" {
#   project = var.project_id
#   role    = "roles/storage.objectViewer"
#   member  = "serviceAccount:${google_service_account.runtime.email}"
# }

# resource "google_project_iam_member" "storage_admin" {
#   project = var.project_id
#   role    = "roles/storage.objectAdmin"
#   member  = "serviceAccount:${google_service_account.runtime.email}"
# }

# Firestore access (uncomment if needed)
# resource "google_project_iam_member" "firestore_user" {
#   project = var.project_id
#   role    = "roles/datastore.user"
#   member  = "serviceAccount:${google_service_account.runtime.email}"
# }

# Cloud SQL access (uncomment if needed)
# resource "google_project_iam_member" "cloudsql_client" {
#   project = var.project_id
#   role    = "roles/cloudsql.client"
#   member  = "serviceAccount:${google_service_account.runtime.email}"
# }

# Secret Manager access (uncomment if needed)
# resource "google_project_iam_member" "secret_accessor" {
#   project = var.project_id
#   role    = "roles/secretmanager.secretAccessor"
#   member  = "serviceAccount:${google_service_account.runtime.email}"
# }

# Pub/Sub publisher (uncomment if needed)
# resource "google_project_iam_member" "pubsub_publisher" {
#   project = var.project_id
#   role    = "roles/pubsub.publisher"
#   member  = "serviceAccount:${google_service_account.runtime.email}"
# }

# Cloud Tasks enqueuer (uncomment if needed)
# resource "google_project_iam_member" "cloudtasks_enqueuer" {
#   project = var.project_id
#   role    = "roles/cloudtasks.enqueuer"
#   member  = "serviceAccount:${google_service_account.runtime.email}"
# }

# BigQuery access (uncomment if needed)
# resource "google_project_iam_member" "bigquery_viewer" {
#   project = var.project_id
#   role    = "roles/bigquery.dataViewer"
#   member  = "serviceAccount:${google_service_account.runtime.email}"
# }
