# main.tf - Cloud Run Service Definition
# Generated by cloudrun-deploy skill

terraform {
  required_version = ">= 1.0"
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = ">= 4.0"
    }
  }
}

provider "google" {
  project = var.project_id
  region  = var.region
}

# Cloud Run Service
resource "google_cloud_run_v2_service" "main" {
  name     = var.service_name
  location = var.region

  template {
    # Service account for runtime
    service_account = google_service_account.runtime.email

    # Scaling configuration
    scaling {
      min_instance_count = var.min_instances
      max_instance_count = var.max_instances
    }

    # Container configuration
    containers {
      image = var.image_url

      # Resource limits
      resources {
        limits = {
          cpu    = var.cpu
          memory = var.memory
        }
        cpu_idle          = var.min_instances == 0  # Scale to zero
        startup_cpu_boost = true
      }

      # Port configuration
      ports {
        container_port = var.port
      }

      # Environment variables (non-secret)
      dynamic "env" {
        for_each = var.env_vars
        content {
          name  = env.key
          value = env.value
        }
      }

      # Secret environment variables
      dynamic "env" {
        for_each = var.secret_env_vars
        content {
          name = env.key
          value_source {
            secret_key_ref {
              secret  = env.value.secret_name
              version = env.value.version
            }
          }
        }
      }

      # Startup probe
      dynamic "startup_probe" {
        for_each = var.startup_probe_path != null ? [1] : []
        content {
          http_get {
            path = var.startup_probe_path
            port = var.port
          }
          initial_delay_seconds = var.startup_probe_initial_delay
          timeout_seconds       = var.startup_probe_timeout
          period_seconds        = var.startup_probe_period
          failure_threshold     = var.startup_probe_failure_threshold
        }
      }

      # Liveness probe (optional)
      dynamic "liveness_probe" {
        for_each = var.liveness_probe_path != null ? [1] : []
        content {
          http_get {
            path = var.liveness_probe_path
            port = var.port
          }
          timeout_seconds = 1
          period_seconds  = 10
        }
      }
    }

    # Timeout
    timeout = "${var.timeout_seconds}s"

    # Max concurrent requests
    max_instance_request_concurrency = var.concurrency

    # VPC configuration (if needed)
    dynamic "vpc_access" {
      for_each = var.vpc_connector != null ? [1] : []
      content {
        connector = var.vpc_connector
        egress    = var.vpc_egress
      }
    }
  }

  # Traffic configuration
  traffic {
    type    = "TRAFFIC_TARGET_ALLOCATION_TYPE_LATEST"
    percent = 100
  }

  # Labels
  labels = var.labels

  depends_on = [
    google_project_service.run,
  ]
}

# Enable Cloud Run API
resource "google_project_service" "run" {
  service            = "run.googleapis.com"
  disable_on_destroy = false
}

# IAM: Allow unauthenticated access (if enabled)
resource "google_cloud_run_v2_service_iam_member" "public" {
  count = var.allow_unauthenticated ? 1 : 0

  location = google_cloud_run_v2_service.main.location
  name     = google_cloud_run_v2_service.main.name
  role     = "roles/run.invoker"
  member   = "allUsers"
}

# Custom domain mapping (if specified)
resource "google_cloud_run_domain_mapping" "main" {
  count = var.custom_domain != null ? 1 : 0

  location = var.region
  name     = var.custom_domain

  metadata {
    namespace = var.project_id
  }

  spec {
    route_name = google_cloud_run_v2_service.main.name
  }
}
