# outputs.tf - Output Values
# Generated by cloudrun-deploy skill

output "service_url" {
  description = "URL of the deployed Cloud Run service"
  value       = google_cloud_run_v2_service.main.uri
}

output "service_name" {
  description = "Name of the Cloud Run service"
  value       = google_cloud_run_v2_service.main.name
}

output "service_id" {
  description = "Fully qualified service ID"
  value       = google_cloud_run_v2_service.main.id
}

output "latest_revision" {
  description = "Name of the latest revision"
  value       = google_cloud_run_v2_service.main.latest_ready_revision
}

output "runtime_service_account" {
  description = "Email of the runtime service account"
  value       = google_service_account.runtime.email
}

output "custom_domain_status" {
  description = "Status of custom domain mapping (if configured)"
  value       = var.custom_domain != null ? google_cloud_run_domain_mapping.main[0].status : null
}
