# secrets.tf - Secret Manager Resources
# Generated by cloudrun-deploy skill

# Enable Secret Manager API
resource "google_project_service" "secretmanager" {
  service            = "secretmanager.googleapis.com"
  disable_on_destroy = false
}

# ============================================================================
# Secret Resources
# Add secrets as needed for your service
# ============================================================================

# Example secret creation (uncomment and customize)
# resource "google_secret_manager_secret" "api_key" {
#   secret_id = "${var.service_name}-api-key"
#
#   replication {
#     auto {}
#   }
#
#   depends_on = [google_project_service.secretmanager]
# }

# Example secret version (set the actual value via CLI or CI/CD)
# Note: Don't store actual secret values in Terraform files
# Use: gcloud secrets versions add SECRET_NAME --data-file=-
#
# resource "google_secret_manager_secret_version" "api_key" {
#   secret      = google_secret_manager_secret.api_key.id
#   secret_data = "SET_VIA_CLI"  # Placeholder - set via gcloud CLI
# }

# Grant runtime service account access to secrets
# resource "google_secret_manager_secret_iam_member" "api_key_access" {
#   secret_id = google_secret_manager_secret.api_key.id
#   role      = "roles/secretmanager.secretAccessor"
#   member    = "serviceAccount:${google_service_account.runtime.email}"
# }

# ============================================================================
# Dynamic Secret Access (for secrets defined in variables)
# ============================================================================

# Grant access to all secrets referenced in secret_env_vars
resource "google_secret_manager_secret_iam_member" "runtime_access" {
  for_each = var.secret_env_vars

  secret_id = each.value.secret_name
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.runtime.email}"
}
