# variables.tf - Input Variable Declarations
# Generated by cloudrun-deploy skill

# ============================================================================
# Service Identity
# ============================================================================

variable "service_name" {
  description = "Name of the Cloud Run service"
  type        = string

  validation {
    condition     = can(regex("^[a-z][a-z0-9-]{0,62}$", var.service_name))
    error_message = "Service name must be lowercase, start with a letter, contain only letters, numbers, and hyphens, and be max 63 characters."
  }
}

variable "labels" {
  description = "Labels to apply to the service"
  type        = map(string)
  default     = {}
}

# ============================================================================
# GCP Target
# ============================================================================

variable "project_id" {
  description = "GCP project ID"
  type        = string
}

variable "region" {
  description = "GCP region for Cloud Run"
  type        = string
  default     = "europe-west2"
}

# ============================================================================
# Container Image
# ============================================================================

variable "image_url" {
  description = "Full URL of the container image (e.g., gcr.io/project/service:tag)"
  type        = string
}

variable "port" {
  description = "Port the container listens on"
  type        = number
  default     = 8080
}

# ============================================================================
# Resource Allocation
# ============================================================================

variable "memory" {
  description = "Memory allocation (e.g., 512Mi, 1Gi, 2Gi)"
  type        = string
  default     = "512Mi"
}

variable "cpu" {
  description = "CPU allocation (1, 2, 4, 6, or 8)"
  type        = string
  default     = "1"
}

variable "timeout_seconds" {
  description = "Maximum request timeout in seconds (1-3600)"
  type        = number
  default     = 300

  validation {
    condition     = var.timeout_seconds >= 1 && var.timeout_seconds <= 3600
    error_message = "Timeout must be between 1 and 3600 seconds."
  }
}

variable "min_instances" {
  description = "Minimum number of instances (0 = scale to zero)"
  type        = number
  default     = 0
}

variable "max_instances" {
  description = "Maximum number of instances"
  type        = number
  default     = 10
}

variable "concurrency" {
  description = "Maximum concurrent requests per instance"
  type        = number
  default     = 80
}

# ============================================================================
# Environment Variables
# ============================================================================

variable "env_vars" {
  description = "Non-secret environment variables"
  type        = map(string)
  default     = {}
}

variable "secret_env_vars" {
  description = "Secret environment variables (from Secret Manager)"
  type = map(object({
    secret_name = string
    version     = string
  }))
  default = {}
}

# ============================================================================
# Networking & Access Control
# ============================================================================

variable "allow_unauthenticated" {
  description = "Allow public access without authentication"
  type        = bool
  default     = false
}

variable "ingress" {
  description = "Ingress settings: all, internal, internal-and-cloud-load-balancing"
  type        = string
  default     = "all"

  validation {
    condition     = contains(["all", "internal", "internal-and-cloud-load-balancing"], var.ingress)
    error_message = "Ingress must be one of: all, internal, internal-and-cloud-load-balancing."
  }
}

variable "custom_domain" {
  description = "Custom domain to map to this service"
  type        = string
  default     = null
}

variable "vpc_connector" {
  description = "VPC connector for private network access"
  type        = string
  default     = null
}

variable "vpc_egress" {
  description = "VPC egress setting: all-traffic or private-ranges-only"
  type        = string
  default     = "private-ranges-only"
}

# ============================================================================
# Health Checks
# ============================================================================

variable "startup_probe_path" {
  description = "HTTP path for startup probe"
  type        = string
  default     = "/"
}

variable "startup_probe_initial_delay" {
  description = "Seconds before first startup probe"
  type        = number
  default     = 0
}

variable "startup_probe_timeout" {
  description = "Seconds to wait for startup probe response"
  type        = number
  default     = 1
}

variable "startup_probe_period" {
  description = "Seconds between startup probes"
  type        = number
  default     = 3
}

variable "startup_probe_failure_threshold" {
  description = "Number of failures before marking unhealthy"
  type        = number
  default     = 1
}

variable "liveness_probe_path" {
  description = "HTTP path for liveness probe (null to disable)"
  type        = string
  default     = null
}
