# Node.js Dockerfile
# Generated by cloudrun-deploy skill

FROM node:20-slim

# Set working directory
WORKDIR /app

# Copy package files first (better layer caching)
COPY package*.json ./

# Install dependencies (production only)
RUN npm ci --only=production

# Copy application code
COPY . .

# Create non-root user for security
USER node

# Expose port (Cloud Run uses PORT env var)
ENV PORT=8080
EXPOSE ${PORT}

# Start the application
CMD ["node", "index.js"]
